List<String> certifications = [
  "AWS (Amazon Web Services)",
  "Microsoft",
  "Google Cloud",
  "Cisco (CCNA, CCNP)",
  "CompTIA",
  "Oracle",
  "Red Hat",
  "Certified Information Systems Auditor (CISA)",
  "Certified Information Systems Security Professional (CISSP)",
  "Certified Ethical Hacker (CEH)",
  "ISACA (CISM)",
  "ITIL (AXELOS)",
  "VMware",
  "IBM",
  "Palo Alto Networks",
  "Scrum Alliance (CSM)",
  "Scrum.org (PSM)",
  "PMI (Project Management Institute)",
  "Google (Android Developer)",
  "Microsoft (Azure Developer, Power Platform)",
  "Coursera (Specializations by top universities)",
  "edX (Certificates by MIT, Harvard, etc.)",
  "Udemy",
  "Kubernetes (CKA, CKAD)",
  "Linux Professional Institute (LPIC)",
  "Cloudera",
  "Salesforce",
  "Tableau",
  "DataCamp",
  "Unity",
  "Autodesk",
  "Adobe Certified Professional",
  "HubSpot Academy",
  "LinkedIn Learning",
  "PMP (Project Management Professional)",
  "CAPM (Certified Associate in Project Management)",
  "Certified Scrum Master (CSM)",
  "Agile Alliance",
  "TOGAF (The Open Group)",
  "COBIT",
  "Six Sigma (Green Belt, Black Belt)",
  "Lean Management Certification",
  "PRINCE2 (AXELOS)",
  "Certified Financial Planner (CFP)",
  "Chartered Financial Analyst (CFA)",
  "Google Analytics Academy",
  "Digital Marketing Institute",
  "Facebook Blueprint",
  "SEMrush Academy",
  "Hootsuite Academy",
];
