const List<String> degreeFields = [
  // Primary and Secondary Education
  "High School Diploma",
  "Secondary School Certificate (SSC)",
  "Higher Secondary Certificate (HSC)",
  "General Educational Development (GED)",

  // Undergraduate Degrees
  "Associate of Arts (AA)",
  "Associate of Science (AS)",
  "Associate of Applied Science (AAS)",
  "Bachelor of Arts (BA)",
  "Bachelor of Science (BSc)",
  "Bachelor of Commerce (BCom)",
  "Bachelor of Business Administration (BBA)",
  "Bachelor of Computer Applications (BCA)",
  "Bachelor of Technology (BTech)",
  "Bachelor of Engineering (BE)",
  "Bachelor of Fine Arts (BFA)",
  "Bachelor of Design (BDes)",
  "Bachelor of Architecture (BArch)",
  "Bachelor of Laws (LLB)",
  "Bachelor of Medicine and Bachelor of Surgery (MBBS)",
  "Bachelor of Pharmacy (BPharm)",
  "Bachelor of Nursing (BN)",
  "Bachelor of Education (BEd)",
  "Bachelor of Social Work (BSW)",

  // Postgraduate Degrees
  "Master of Arts (MA)",
  "Master of Science (MSc)",
  "Master of Commerce (MCom)",
  "Master of Business Administration (MBA)",
  "Master of Computer Applications (MCA)",
  "Master of Technology (MTech)",
  "Master of Engineering (ME)",
  "Master of Fine Arts (MFA)",
  "Master of Design (MDes)",
  "Master of Architecture (MArch)",
  "Master of Laws (LLM)",
  "Doctor of Medicine (MD)",
  "Master of Pharmacy (MPharm)",
  "Master of Public Administration (MPA)",
  "Master of Social Work (MSW)",
  "Master of Education (MEd)",

  // Doctoral and Research Degrees
  "Doctor of Philosophy (PhD)",
  "Doctor of Science (DSc)",
  "Doctor of Engineering (DEng)",
  "Doctor of Business Administration (DBA)",
  "Doctor of Education (EdD)",
  "Doctor of Medicine (MD)",
  "Doctor of Pharmacy (PharmD)",

  // Diplomas and Certifications
  "Diploma in Engineering",
  "Diploma in Computer Science",
  "Diploma in Business Management",
  "Diploma in Graphic Design",
  "Postgraduate Diploma in Management (PGDM)",
  "Diploma in Digital Marketing",
  "Certified Public Accountant (CPA)",
  "Chartered Financial Analyst (CFA)",
  "Project Management Professional (PMP)",
  "Certified Ethical Hacker (CEH)",
  "Cisco Certified Network Associate (CCNA)",
  "Microsoft Certified: Azure Solutions Architect Expert",
  "AWS Certified Solutions Architect",
  "Google Certified Professional Data Engineer",
  "Six Sigma Green Belt",
  "Six Sigma Black Belt",
  "Scrum Master Certification (CSM)",

  // Vocational and Specialized Certifications
  "Vocational Training Certificate",
  "Certificate in Data Science",
  "Certificate in Machine Learning",
  "Certificate in Web Development",
  "Certificate in Blockchain Technology",
  "Certificate in Cybersecurity",
  "Certificate in Cloud Computing",
  "Certificate in Artificial Intelligence",
  "Certificate in Business Analytics",
  "Certificate in UX/UI Design",
  "Certificate in Game Development",
  "Certificate in Animation",
  "Certificate in Financial Modeling",
  "Certificate in Photography",
  "Certificate in Film Editing",
  "Certificate in Supply Chain Management",

  // International Qualifications
  "International Baccalaureate (IB)",
  "General Certificate of Secondary Education (GCSE)",
  "A-Levels",
  "O-Levels",
  "European Baccalaureate (EB)",
  "HND (Higher National Diploma)",
  "NVQ (National Vocational Qualification)",

  // Others
  "Professional Development Courses",
  "Online Course Certifications (Coursera, edX, Udemy, etc.)",
  "MOOCs (Massive Open Online Courses)",
  "Technical Bootcamps",
  "Trade School Diplomas"
];
