const List<String> jobTitles = [
  "Software Engineer",
  "Data Scientist",
  "Product Manager",
  "Frontend Developer",
  "Backend Developer",
  "Fullstack Developer",
  "DevOps Engineer",
  "Cloud Architect",
  "Cybersecurity Analyst",
  "Network Administrator",
  "IT Support Specialist",
  "Database Administrator",
  "Machine Learning Engineer",
  "AI Researcher",
  "Blockchain Developer",
  "Game Developer",
  "Mobile App Developer",
  "UX Designer",
  "UI Engineer",
  "Graphic Designer",
  "Motion Graphics Artist",
  "Digital Marketing Manager",
  "Content Strategist",
  "Social Media Manager",
  "SEO Analyst",
  "Marketing Coordinator",
  "Sales Executive",
  "Account Manager",
  "Customer Success Manager",
  "Business Analyst",
  "Financial Analyst",
  "Risk Manager",
  "HR Manager",
  "Talent Acquisition Specialist",
  "Compensation and Benefits Manager",
  "Training and Development Manager",
  "Project Manager",
  "Scrum Master",
  "Agile Coach",
  "Supply Chain Manager",
  "Logistics Coordinator",
  "Procurement Specialist",
  "Operations Manager",
  "Quality Assurance Analyst",
  "Test Automation Engineer",
  "Product Designer",
  "Mechanical Engineer",
  "Civil Engineer",
  "Electrical Engineer"
];
