const List<String> skillSuggestions = [
  "Artificial Intelligence (AI)",
  "Machine Learning (ML)",
  "Data Science",
  "Data Analytics",
  "Big Data",
  "Cloud Computing",
  "Cybersecurity",
  "Blockchain Technology",
  "Internet of Things (IoT)",
  "Virtual Reality (VR)",
  "Augmented Reality (AR)",
  "Natural Language Processing (NLP)",
  "Robotic Process Automation (RPA)",
  "Deep Learning",
  "Computer Vision",
  "Embedded Systems",
  "Quantum Computing",
  "Game Development",
  "Software Engineering",
  "Full-Stack Development",
  "Front-End Development",
  "Back-End Development",
  "Mobile Application Development",
  "Web Development",
  "UI/UX Design",
  "DevOps",
  "Network Engineering",
  "Database Administration",
  "Database Architecture",
  "System Architecture",
  "Software Testing",
  "API Development",
  "Business Intelligence (BI)",
  "Ethical Hacking",
  "Penetration Testing",
  "Application Security",
  "IT Infrastructure",
  "Automation Testing",
  "Blockchain Development",
  "Cloud Architecture",
  "E-Commerce Development",
  "Game Design",
  "Web Accessibility",
  "Digital Marketing",
  "Product Management",
  "Project Management",
  "Tech Consulting",
  "Technology Solutions Architecture",

  // Business & Management
  "Business Administration",
  "Finance Management",
  "Human Resources (HR)",
  "Operations Management",
  "Marketing Management",
  "Supply Chain Management",
  "Product Management",
  "Brand Management",
  "Sales & Business Development",
  "Project Management",
  "Change Management",
  "Strategy Consulting",
  "Management Consulting",
  "Financial Analysis",
  "Corporate Finance",
  "Risk Management",
  "Business Analytics",
  "Public Relations",
  "Customer Relationship Management (CRM)",
  "Leadership Development",
  "People Management",
  "Market Research",
  "Entrepreneurship",
  "Organizational Development",
  "Corporate Governance",
  "Financial Planning",
  "Investment Banking",
  "Mergers & Acquisitions",
  "Business Operations",
  "Agile Methodology",
  "Lean Management",
  "Revenue Operations",
  "Sales Enablement",

  // Marketing & Communications
  "Content Marketing",
  "Social Media Marketing",
  "Digital Marketing",
  "SEO (Search Engine Optimization)",
  "SEM (Search Engine Marketing)",
  "Email Marketing",
  "Influencer Marketing",
  "Affiliate Marketing",
  "Brand Management",
  "Product Marketing",
  "Creative Writing",
  "Public Relations",
  "Market Research",
  "Advertising",
  "Event Marketing",
  "Video Production",
  "Copywriting",
  "Creative Direction",
  "Communication Strategy",
  "Online Advertising",
  "Customer Acquisition",
  "Paid Media Campaigns",
  "Lead Generation",
  "Web Analytics",
  "Community Management",
  "Marketing Strategy",

  // Finance & Accounting
  "Financial Accounting",
  "Management Accounting",
  "Taxation",
  "Audit & Assurance",
  "Financial Reporting",
  "Budgeting & Forecasting",
  "Investment Banking",
  "Corporate Finance",
  "Venture Capital",
  "Private Equity",
  "Financial Analysis",
  "Risk Management",
  "Financial Planning & Analysis (FP&A)",
  "Derivatives Trading",
  "Credit Risk",
  "Financial Modeling",
  "Portfolio Management",
  "Internal Auditing",
  "Tax Compliance",
  "Cost Accounting",
  "Treasury Management",

  // Healthcare & Life Sciences
  "Medical Research",
  "Clinical Research",
  "Healthcare Management",
  "Pharmacology",
  "Pharmacy Management",
  "Nursing",
  "Public Health",
  "Medical Device Development",
  "Bioinformatics",
  "Genetics",
  "Biotechnology",
  "Molecular Biology",
  "Health Data Analytics",
  "Epidemiology",
  "Medical Writing",
  "Healthcare Policy",
  "Telemedicine",
  "Patient Care",
  "Health Informatics",
  "Hospital Administration",
  "Health Economics",
  "Healthcare IT",

  // Design & Creative Arts
  "Graphic Design",
  "Web Design",
  "UI/UX Design",
  "Game Design",
  "3D Modeling",
  "Animation",
  "Motion Graphics",
  "Video Editing",
  "Photography",
  "Fashion Design",
  "Interior Design",
  "Product Design",
  "Industrial Design",
  "Digital Art",
  "Branding & Identity Design",
  "Illustration",
  "Textile Design",
  "Print Design",
  "Packaging Design",
  "Advertising Design",
  "Visual Arts",

  // Education & Training
  "Teaching",
  "Curriculum Development",
  "Educational Leadership",
  "Instructional Design",
  "E-Learning",
  "Tutoring",
  "Higher Education Administration",
  "Special Education",
  "Training & Development",
  "Learning & Development",
  "Corporate Training",
  "Online Course Development",
  "Student Counseling",
  "Career Counseling",
  "Academic Research",
  "Teacher Education",
  "Behavioral Education",

  // Legal & Compliance
  "Corporate Law",
  "Intellectual Property (IP) Law",
  "Criminal Law",
  "Family Law",
  "Contract Law",
  "Employment Law",
  "Tax Law",
  "Mergers & Acquisitions Law",
  "Regulatory Compliance",
  "Litigation",
  "Real Estate Law",
  "Environmental Law",
  "Immigration Law",
  "Bankruptcy Law",
  "Human Rights Law",
  "Corporate Governance",
  "Antitrust Law",
  "Dispute Resolution",

  // Science & Engineering
  "Civil Engineering",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Chemical Engineering",
  "Aerospace Engineering",
  "Environmental Engineering",
  "Industrial Engineering",
  "Automotive Engineering",
  "Biochemical Engineering",
  "Petroleum Engineering",
  "Structural Engineering",
  "Materials Science",
  "Physics",
  "Chemistry",
  "Biology",
  "Mathematics",
  "Geology",
  "Astronomy",
  "Agricultural Science",
  "Marine Biology",
  "Forestry",
  "Meteorology",
  "Pharmaceutical Sciences",
  "Nanotechnology",
  "Renewable Energy",

  // Human Resources & Talent Management
  "Talent Acquisition",
  "Recruitment",
  "Employee Relations",
  "Training & Development",
  "Compensation & Benefits",
  "HR Analytics",
  "Employee Engagement",
  "Organizational Development",
  "Performance Management",
  "HR Compliance",
  "Payroll Management",
  "Workplace Diversity & Inclusion",
  "HRIS (Human Resources Information System)",
  "Employee Wellbeing",
  "Labor Relations",
  "Onboarding",
  "Leadership Development",
  "Talent Retention",
  "Succession Planning",

  // Supply Chain & Logistics
  "Supply Chain Management",
  "Logistics Management",
  "Inventory Management",
  "Procurement",
  "Warehouse Management",
  "Distribution & Transportation",
  "Vendor Management",
  "Demand Planning",
  "Supply Chain Analytics",
  "Logistics Optimization",
  "Operations Management",
  "Freight Forwarding",
  "Material Management",
  "Production Planning",
  "Sourcing & Purchasing",
  "Import & Export",
  "Supply Chain Risk Management",
  "Supply Chain Automation",
  "Contract Management",
  "International Trade",
  "GraphQL",
  "Docker",
  "Kubernetes",
  "AWS",
  "Microservices Architecture"
];
