const List<String> studyFields = [
  "Computer Science",
  "Information Technology",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Electronics and Communication Engineering",
  "Artificial Intelligence and Machine Learning",
  "Data Science",
  "Software Engineering",
  "Cybersecurity",
  "Robotics",
  "Biotechnology",
  "Aerospace Engineering",
  "Environmental Science",
  "Physics",
  "Chemistry",
  "Mathematics",
  "Economics",
  "Business Administration",
  "Marketing",
  "Finance",
  "Human Resource Management",
  "Operations Management",
  "Law",
  "Medicine",
  "Nursing",
  "Pharmacy",
  "Architecture",
  "Fine Arts",
  "Music",
  "Performing Arts",
  "Journalism and Mass Communication",
  "Education",
  "Psychology",
  "Sociology",
  "Political Science",
  "History",
  "Geography",
  "Anthropology",
  "Philosophy",
  "English Literature",
  "Linguistics",
  "Agriculture",
  "Veterinary Science",
  "Forestry",
  "Horticulture",
  "Food Technology",
  "Fashion Designing",
  "Textile Engineering",
  "Hospitality Management",
  "Tourism Management",
  "Public Health",
  "Sports Science",
  "Physical Education",
  "Astronomy",
  "Marine Biology",
  "Geology",
  "Urban Planning",
  "Graphic Design",
  "Film Making",
  "Animation and Multimedia",
  "Game Design",
  "Ethics and Governance",
  "Cloud Computing",
  "Blockchain Technology",
  "Internet of Things",
  "Biomedical Engineering",
  "Renewable Energy",
  "Supply Chain Management",
  "Event Management",
  "Social Work",
  "Counseling",
  "Criminology",
  "Forensic Science",
  "Statistics",
  "Actuarial Science",
  "Material Science",
  "Nanotechnology",
  "Energy Engineering",
  "Industrial Design",
  "Product Management",
  "Artificial Neural Networks",
  "Database Management",
  "Quantum Computing",
  "Cognitive Science",
  "Zoology",
  "Botany",
];
